# Generated by Django 2.0.5 on 2018-05-20 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hospital',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
