# Generated by Django 2.0.5 on 2018-06-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='user',
            new_name='username_id',
        ),
    ]
