# Generated by Django 2.0.5 on 2018-05-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='apoti_index',
            new_name='apoti_true',
        ),
    ]
