# Generated by Django 2.0.5 on 2018-06-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_auto_20180520_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='apoti_true',
            new_name='atopy_true',
        ),
    ]
