# Generated by Django 2.0.5 on 2018-06-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_auto_20180603_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
